//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM.Wrapper
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IMResource_Dev {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IMResource_Dev() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IM.Wrapper.IMResource.Dev", typeof(IMResource_Dev).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USEOMCDP040\Interwoven1.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interwoven2008.
        /// </summary>
        internal static string DownloadPassword {
            get {
                return ResourceManager.GetString("DownloadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us-svcdeviwa1.
        /// </summary>
        internal static string DownloadUserID {
            get {
                return ResourceManager.GetString("DownloadUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interwoven2008.
        /// </summary>
        internal static string IMAdminPassword {
            get {
                return ResourceManager.GetString("IMAdminPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us-svcdeviwa1.
        /// </summary>
        internal static string IMAdminUserID {
            get {
                return ResourceManager.GetString("IMAdminUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to useomapd1003.
        /// </summary>
        internal static string IMServer {
            get {
                return ResourceManager.GetString("IMServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string InitialCatalog {
            get {
                return ResourceManager.GetString("InitialCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to false.
        /// </summary>
        internal static string IntegratedSecurity {
            get {
                return ResourceManager.GetString("IntegratedSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DRMS2011$.
        /// </summary>
        internal static string SqlPassword {
            get {
                return ResourceManager.GetString("SqlPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to idms.
        /// </summary>
        internal static string SqlUserID {
            get {
                return ResourceManager.GetString("SqlUserID", resourceCulture);
            }
        }
    }
}
