//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuditManager.Rep.S2MafService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Server2Object", Namespace="http://schemas.datacontract.org/2004/07/S2ClosureMAFResults")]
    [System.SerializableAttribute()]
    public partial class Server2Object : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngagementNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EngagementNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MafGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MafIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WbDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WbReviewIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WbStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkbookGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkbookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkbookNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientName {
            get {
                return this.ClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNameField, value) != true)) {
                    this.ClientNameField = value;
                    this.RaisePropertyChanged("ClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientNumber {
            get {
                return this.ClientNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientNumberField, value) != true)) {
                    this.ClientNumberField = value;
                    this.RaisePropertyChanged("ClientNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngagementName {
            get {
                return this.EngagementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EngagementNameField, value) != true)) {
                    this.EngagementNameField = value;
                    this.RaisePropertyChanged("EngagementName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EngagementNumber {
            get {
                return this.EngagementNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.EngagementNumberField, value) != true)) {
                    this.EngagementNumberField = value;
                    this.RaisePropertyChanged("EngagementNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MafGuid {
            get {
                return this.MafGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.MafGuidField, value) != true)) {
                    this.MafGuidField = value;
                    this.RaisePropertyChanged("MafGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MafId {
            get {
                return this.MafIdField;
            }
            set {
                if ((this.MafIdField.Equals(value) != true)) {
                    this.MafIdField = value;
                    this.RaisePropertyChanged("MafId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerField, value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partner {
            get {
                return this.PartnerField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerField, value) != true)) {
                    this.PartnerField = value;
                    this.RaisePropertyChanged("Partner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WbDescription {
            get {
                return this.WbDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.WbDescriptionField, value) != true)) {
                    this.WbDescriptionField = value;
                    this.RaisePropertyChanged("WbDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WbReviewId {
            get {
                return this.WbReviewIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WbReviewIdField, value) != true)) {
                    this.WbReviewIdField = value;
                    this.RaisePropertyChanged("WbReviewId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WbStatus {
            get {
                return this.WbStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.WbStatusField, value) != true)) {
                    this.WbStatusField = value;
                    this.RaisePropertyChanged("WbStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkbookGuid {
            get {
                return this.WorkbookGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkbookGuidField, value) != true)) {
                    this.WorkbookGuidField = value;
                    this.RaisePropertyChanged("WorkbookGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkbookId {
            get {
                return this.WorkbookIdField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkbookIdField, value) != true)) {
                    this.WorkbookIdField = value;
                    this.RaisePropertyChanged("WorkbookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkbookName {
            get {
                return this.WorkbookNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkbookNameField, value) != true)) {
                    this.WorkbookNameField = value;
                    this.RaisePropertyChanged("WorkbookName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/S2ClosureMAFResults")]
    [System.SerializableAttribute()]
    public partial class ServiceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCriticalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCritical {
            get {
                return this.IsCriticalField;
            }
            set {
                if ((this.IsCriticalField.Equals(value) != true)) {
                    this.IsCriticalField = value;
                    this.RaisePropertyChanged("IsCritical");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="S2MafService.IMAFService")]
    public interface IMAFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMAFService/GetClosureWBDetails", ReplyAction="http://tempuri.org/IMAFService/GetClosureWBDetailsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(AuditManager.Rep.S2MafService.ServiceException), Action="http://tempuri.org/IMAFService/GetClosureWBDetailsServiceExceptionFault", Name="ServiceException", Namespace="http://schemas.datacontract.org/2004/07/S2ClosureMAFResults")]
        System.Collections.Generic.List<AuditManager.Rep.S2MafService.Server2Object> GetClosureWBDetails(string strGUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMAFService/GetClosureWBDetails", ReplyAction="http://tempuri.org/IMAFService/GetClosureWBDetailsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<AuditManager.Rep.S2MafService.Server2Object>> GetClosureWBDetailsAsync(string strGUID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMAFServiceChannel : AuditManager.Rep.S2MafService.IMAFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MAFServiceClient : System.ServiceModel.ClientBase<AuditManager.Rep.S2MafService.IMAFService>, AuditManager.Rep.S2MafService.IMAFService {
        
        public MAFServiceClient() {
        }
        
        public MAFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MAFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MAFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MAFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<AuditManager.Rep.S2MafService.Server2Object> GetClosureWBDetails(string strGUID) {
            return base.Channel.GetClosureWBDetails(strGUID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<AuditManager.Rep.S2MafService.Server2Object>> GetClosureWBDetailsAsync(string strGUID) {
            return base.Channel.GetClosureWBDetailsAsync(strGUID);
        }
    }
}
